#!/bin/bash

# Timestamp Function
timestamp() {
	date +"%T"
}

# Temporary file for stderr redirects
tmpfile=$(mktemp)

# Build a docker image
buildDocker() {
	echo "🐋	$(timestamp): building image user-service:latest"
	minikube tunnel
	eval $(minikube docker-env)
	docker build -t user-service:latest .
}

# Deploy to Minikube using kubectl
deploy() {
	echo "🌧️	 $(timestamp): deploying to Minikube"
	kubectl delete deployment user-service
	kubectl delete service user-svc
	kubectl apply -f deployment/deployment.yaml
}

# Orchestrate
if [[ $1 = "build" ]]; then
	if [[ $2 = "docker" ]]; then
		if [[ $3 = "deploy" ]]; then
			buildDocker
			deploy
		else
			buildDocker
		fi
		echo "✔️	$(timestamp): complete."
		echo "👋	$(timestamp): exiting..."
	elif [[ $2 = "bin" ]]; then
		build
		echo "✔️	$(timestamp): complete."
		echo "👋	$(timestamp): exiting..."
	else
		echo "🤔   $(timestamp): missing build argument | do you already sign in to docker hub interactive shell?..."
	fi
else
	if [[ $1 = "--help" ]]; then
		echo "build - start a build to produce artifacts"
		echo "	docker - produces docker images"
		echo " 	bin - produces executable binaries"
	else
		echo "🤔	$(timestamp): no arguments passed, type --help for a list of arguments"
	fi
fi
rm -f tmpfile