apiVersion: v1
kind: Secret
metadata:
  name: user-svc-secret
  namespace: default
type: Opaque
data:
  PG_USERNAME: c2dwb3N0Z3Jlcw==
  PG_PASSWORD: d3hrU1ZIZ3IuOXFlREtraA==
  PG_HOST: U0cteGVuZGl0LTg0NC1wZ3NxbC1tYXN0ZXIuc2VydmVycy5tb25nb2RpcmVjdG9yLmNvbQ==
  PG_PORT: NTQzMg==
  PG_DBNAME: dXNlcl9zZXJ2aWNl
  DB_AUTO_CREATE: dHJ1ZQ==
  COMMENT_SERVICE: MC4wLjAuMDo2MDYw